# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyconuk', '0003_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=40)),
                ('room', models.CharField(max_length=40)),
                ('time', models.CharField(max_length=40)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pyconuk.Session')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
