# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyconuk', '0004_scheduleslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='logo_filename',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='twitter_handle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='website',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
