# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyconuk', '0007_page_show_sponsors'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleslot',
            name='chair',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
