# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-28 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyconuk', '0008_scheduleslot_chair'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='slides',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='video',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
