import os
import shutil
import yaml

from django.core.management.base import BaseCommand


class Command(BaseCommand):
    def handle(self, *args, **kwargs):
        shutil.rmtree('schedule')

        with open('schedule.yml') as f:
            schedule = yaml.load(f.read())

        for date in schedule:
            print(date)
            for room in schedule[date]:
                print('  {}'.format(room))
                for time in schedule[date][room]:
                    print('    {}'.format(time))
                    if schedule[date][room][time]:
                        session = schedule[date][room][time]
                        print('      {}'.format(session))

                        fields = {
                            'date': date,
                            'time': time,
                            'room': room,
                        }

                        if session[:6] == 'talks/' or session[:10] == 'workshops/':
                            fields['session'] = session
                        else:
                            fields['title'] = session

                        dir_path = os.path.join('schedule', date, room)
                        os.makedirs(dir_path, exist_ok=True)
                        with open(os.path.join(dir_path, time), 'w') as f:
                            f.write('# Do not edit!  This file is generated by the parseschedule command.\n')
                            f.write('# To make a change to the schedule, change schedule.yml, and run\n')
                            f.write('#\n')
                            f.write('#   python manage.py parseschedule\n')
                            f.write('\n')
                            f.write(yaml.dump(fields, default_flow_style=False))
